import Header from "@/app/components/header/header";
import Footer from "../components/footer/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <div className={"relative w-full h-full "}>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
