import Header from "@/app/components/header/header";
import Footer from "@/app/components/footer/footer";
import {createStore} from "@/app/redux/store";
import { Provider } from "react-redux";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const store = createStore();
  return (
		<div className={"relative w-full h-full "}>
			<Provider store={store}>
				<Header />
				{children}
				<Footer />
			</Provider>
		</div>
	);
}
