import Header from "@/app/components/header/header";
import Footer from "@/app/components/footer/footer";
import StoreProvider from "@/app/redux/provider";
import ToastProvider from "../components/toasty/toastProvider";
import { HandleOnComplete } from "@/app/libs/router-events";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
        <div className={"relative w-full h-full "}>
          <StoreProvider>
            <ToastProvider>
              <Header />
              {children}
              <Footer />
            </ToastProvider>
          </StoreProvider>
        </div>
        <HandleOnComplete />
    </>
  );
}
